# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: readit
      MYSQL_USER: tomek
      MYSQL_PASSWORD: secret
    volumes:
      - ./data:/data/db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080